#output   = "my_models"
wipe     = true
no-tests = true
add-enum-types = true

[mysql]
  dbname  = "hello"
  host    = "localhost"
  port    = 3306
  user    = "boiler"
  pass    = "boiler"
  sslmode = "false"
  tinyint_as_int = true

[auto-columns]
  created = "createdAt"
  updated = "updatedAt"